# Generated by Django 5.0.6 on 2024-06-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
