# Generated by Django 5.0.6 on 2024-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0002_alter_noticia_options_alter_noticia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autorCargo',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='noticia',
            name='autorCitacao',
            field=models.TextField(default='', max_length=255),
        ),
    ]
