# Generated by Django 5.0.6 on 2024-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0003_noticia_autorcargo_noticia_autorcitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='citacao',
            field=models.TextField(default='', max_length=255),
        ),
    ]
