# Generated by Django 5.0.6 on 2024-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0004_noticia_citacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autorCargo',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autorCitacao',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='description',
            field=models.TextField(),
        ),
    ]
