# Generated by Django 5.0.6 on 2024-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0005_alter_noticia_autorcargo_alter_noticia_autorcitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='dataEvento',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='citacao',
            field=models.TextField(default='', max_length=500),
        ),
    ]
