# Generated by Django 5.0.6 on 2024-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0006_noticia_dataevento_alter_noticia_citacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
