# Generated by Django 5.0.6 on 2024-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0008_bancodealimentacao_carta_casamento_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancodealimentacao',
            options={'verbose_name_plural': 'Banco De Alimentação'},
        ),
        migrations.AlterField(
            model_name='casamento',
            name='telefone',
            field=models.CharField(max_length=65),
        ),
    ]
