# Generated by Django 5.0.6 on 2024-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0009_alter_bancodealimentacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancodealimentacao',
            name='telefone',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='carta',
            name='telefone',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='telefone',
            field=models.CharField(max_length=65),
        ),
    ]
