# Generated by Django 5.0.6 on 2024-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0010_alter_bancodealimentacao_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('dataAtividade', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('presidente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Devem',
            },
        ),
        migrations.CreateModel(
            name='Homens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('dataAtividade', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('presidente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Homens',
            },
        ),
        migrations.CreateModel(
            name='Mocidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('dataAtividade', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('presidente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mocidade',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('dataAtividade', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('presidente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Musica',
            },
        ),
        migrations.CreateModel(
            name='Senhoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('dataAtividade', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('presidente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Senhoras',
            },
        ),
    ]
