# Generated by Django 5.0.6 on 2024-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0011_devem_homens_mocidade_musica_senhoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='devem',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='homens',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='mocidade',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='musica',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='senhoras',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
    ]
