# Generated by Django 5.1.1 on 2025-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0012_devem_horario_homens_horario_mocidade_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='foi_feita',
            field=models.BooleanField(default=False),
        ),
    ]
