# Generated by Django 5.1.1 on 2025-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0013_carta_data_solicitacao_carta_foi_feita'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
