# Generated by Django 5.1.1 on 2025-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0014_carta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='status',
        ),
        migrations.AddField(
            model_name='carta',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
