# Generated by Django 5.1.1 on 2025-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0015_remove_carta_status_carta_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancodealimentacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
