# Generated by Django 5.1.1 on 2025-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0016_bancodealimentacao_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
