# Generated by Django 5.1.1 on 2025-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0017_carta_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
