# Generated by Django 5.1.1 on 2025-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0018_mensagem_created_at_newsletter_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adolescentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('dataAtividade', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('horario', models.TimeField(default='00:00')),
                ('descricao', models.TextField()),
                ('presidente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Adolescentes',
            },
        ),
    ]
