# Generated by Django 5.1.1 on 2025-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0020_department_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='noticia/%Y/%m/%d/'),
        ),
    ]
