# Generated by Django 5.1.1 on 2025-08-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0022_cartarecebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('emergencia_nome1', models.CharField(blank=True, max_length=255)),
                ('emergencia_telefone1', models.CharField(blank=True, max_length=20)),
                ('emergencia_nome2', models.CharField(blank=True, max_length=255)),
                ('emergencia_telefone2', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('metodo_pagamento', models.CharField(choices=[('mao', 'Dinheiro em espécie'), ('transferencia', 'Transferência Bancária')], max_length=20)),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprovativo_transferencia', models.FileField(blank=True, null=True, upload_to='comprovativos/')),
                ('referencia_pagamento', models.CharField(editable=False, max_length=20, unique=True)),
                ('pago', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webiel.atividade')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webiel.department')),
            ],
            options={
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
