# Generated by Django 5.1.1 on 2025-08-14 10:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0023_atividade_inscricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='webiel.atividade'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='comprovativo_transferencia',
            field=models.FileField(blank=True, null=True, upload_to='comprovativos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='webiel.department'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='emergencia_nome1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='emergencia_nome2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='emergencia_telefone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='emergencia_telefone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='referencia_pagamento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['email'], name='webiel_insc_email_e60bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['pago'], name='webiel_insc_pago_52f997_idx'),
        ),
    ]
