# Generated by Django 5.1.1 on 2025-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0024_alter_inscricao_options_remove_inscricao_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
