# Generated by Django 5.1.1 on 2025-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0025_atividade_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartarecebida',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
