# Generated by Django 5.1.1 on 2025-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0026_cartarecebida_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='tipo_pagamento',
            field=models.CharField(choices=[('avista', 'Pagamento à Vista'), ('parcelado', 'Pagamento Parcelado')], default='avista', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
