# Generated by Django 5.1.1 on 2025-08-20 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0027_inscricao_nome_conjuge_inscricao_numero_parcelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_esperada', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='comprovativos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='webiel.inscricao')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('inscricao', 'numero')},
            },
        ),
    ]
