# Generated by Django 5.1.1 on 2025-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0028_prestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
