# Generated by Django 5.1.1 on 2025-08-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiel', '0029_prestacao_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacao',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('mao', 'Dinheiro em Espécie'), ('transferencia', 'Transferência Bancária')], max_length=20, null=True),
        ),
    ]
